name: Sync Forms & Metadata to Destination Repo

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Destination Repository
        uses: actions/checkout@v4
        with:
          repository: METS-Programme/ugandaemr-metadata
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/mohuganda/openmrs-module-ugandaemr.git || true
          git fetch upstream --tags

      - name: Force Overwrite Destination Repo with Upstream Changes
        run: |
          git fetch upstream master
          git reset --hard upstream/master  # Force overwrite of destination with upstream

      - name: Configure Sparse Checkout
        run: |
          git sparse-checkout init --cone
          git sparse-checkout set \
            omod/src/main/webapp/resources/htmlforms \
            omod/src/main/webapp/resources/jsonforms \
            api/src/main/resources/metadata
          git checkout --sparse  # Ensures correct application of sparse-checkout

      - name: Ensure Target Directories Exist
        run: |
          test -
